#\u662F\u5426\u5EA7\u4F4D\u5FAE\u670D\u52A1\u6CE8\u518C\u5230\u554A\u6CE8\u518C\u4E2D\u5FC3
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
server:
  port: 2001
spring:
  application:
    name: eureka-server
feign:
  hystrix:
    enabled: true