spring:
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: -1
        max-idle: 500
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 20000




